name: Get Docker Image Tags

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: '请填写docker镜像名称'
        required: true
        default: 'apache/kafka'
      tag_name:
        description: '请填写tag的关键字'
        required: false
        default: ''
jobs:
  get_tags:
    runs-on: ubuntu-latest
    steps:
    - name: show url
      run: |
        image="${{ github.event.inputs.docker_image }}"
        name="${{ github.event.inputs.tag_name }}"
        echo "https://registry.hub.docker.com/v2/repositories/$image/tags?page=1&page_size=100&name=$name"
    - name: get image tags   
      run: |
        image="${{ github.event.inputs.docker_image }}"
        name="${{ github.event.inputs.tag_name }}"
        curl -L -s "https://registry.hub.docker.com/v2/repositories/$image/tags?page=1&page_size=100&name=$name"       
