name: Get Docker Image Tags

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: '请填写docker镜像名称'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表
jobs:
  get_tags:
    runs-on: ubuntu-latest
    steps:
    - name: show url
      run: echo "https://registry.hub.docker.com/v2/repositories/library/zookeeper/tags"   
    - name: get image tags
      run: curl -L -s "https://registry.hub.docker.com/v2/repositories/library/zookeeper/tags"       
