name: Get Docker Image Tags

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: '请填写docker镜像名称'
        required: true
        default: 'apache/kafka'  # 设置默认的 Docker 镜像列表
jobs:
  get_tags:
    runs-on: ubuntu-latest
    steps:
    - name: get image tags
      run: curl -L -s "https://registry.hub.docker.com/v2/repositories/$docker_image/tags?page=2&page_size=100"       
