name: Get Docker Image Tags

on:
  workflow_dispatch:
    inputs:
      docker_image:
        description: '请填写docker镜像名称'
        required: true
        default: 'apache/kafka'  # 设置默认的 Docker 镜像列表
jobs:
  get_tags:
    runs-on: ubuntu-latest
    steps:
    - name: show url
      run: |
        image="${{ github.event.inputs.docker_image }}"
        echo "https://registry.hub.docker.com/v2/repositories/$image/tags?page=1&page_size=100"
    - name: get image tags   
      run: |
        image="${{ github.event.inputs.docker_image }}"
        curl -L -s "https://registry.hub.docker.com/v2/repositories/$image/tags?page=1&page_size=100"       
